export const FORM_SUBMIT = 'FORM_SUBMIT';
export const CHANGE_NEW_IN_DAYS = 'CHANGE_NEW_IN_DAYS';
export const CHANGE_KEYWORDS = 'CHANGE_KEYWORDS';
export const CLEAR_KEYWORDS = 'CLEAR_KEYWORDS';

// Exclusion groups actions
export const ADD_EXCLUSION_GROUP = 'ADD_EXCLUSION_GROUP';
export const REMOVE_EXCLUSION_GROUP = 'REMOVE_EXCLUSION_GROUP';
export const UPDATE_EXCLUSION_GROUP = 'UPDATE_EXCLUSION_GROUP';
export const ADD_WORD_TO_GROUP = 'ADD_WORD_TO_GROUP';
export const REMOVE_WORD_FROM_GROUP = 'REMOVE_WORD_FROM_GROUP';
export const TOGGLE_GROUP_ENABLED = 'TOGGLE_GROUP_ENABLED';
